name: Build SoulEvents Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Compile plugin
        run: |
          mkdir -p build/classes
          javac -source 1.8 -target 1.8 -d build/classes $(find src -name "*.java")
          cp resources/plugin.yml build/classes/

      - name: Create JAR
        run: |
          cd build/classes
          jar cf ../../SoulEvents.jar .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SoulEvents.jar
          path: SoulEvents.jar
